name: ainews-infra

services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    platform: linux/amd64 # 强制使用 AMD64 架构
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=ainews
      - NACOS_AUTH_TOKEN=LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUE5dXVmUjJpUlFHeGNZQTVkVVBqL0hORUc5SVFOQ2x5cUN6eHk4ME1Nc3A4c0xPa0V2N0RTCjY0ektSQkcrcjVWaERGS0YzRXA5OUFycm9MTjdxVVFLeTRjVWl0RnNRU0xYWGJ5L0t6WjdDUW9xOHgwS3U5dmNKOGtVTUQKaEpLK202N2YrcUs0SGxWNlp0c1puQWlFdW5BTTVkRTloZVFQT3hUZXlEd1RjcnBIZE8rQkFmbVFYUm9LbXVZWERlZGFWSgpTRFlzNlhzQThVeWpkQUxpcEpGNmZudnl2UDRFRWZzZ0dRWE9KcjBJUkJ3Q3JvaHU4NFBGeU93UDJ5KzBIcW12NVR0aXNWCjBBVjJNdy95clY0blBEUlRmeC9zdUlyOFRlUjhxRCt4ZUs4SmxZUGtQSXgvaGRsRkF1UzUrcngyWFBUR01FK1VQTUhxMUkKdmhVbkRFc0Jud0FBQThqRXNMN2x4TEMrNVFBQUFBZHpjMmd0Y25OaEFBQUJBUUQyNjU5SGFKRkFiRnhnRGwxUStQOGMwUQpiMGhBMEtYS29MUEhMelF3eXlueXdzNlFTL3NOTHJqTXBFRWI2dmxXRU1Vb1hjU24zMEN1dWdzM3VwUkFyTGh4U0swV3hCCkl0ZGR2TDhyTm5zSkNpcnpIUXE3Mjl3bnlSUXdPRWtyNmJydC82b3JnZVZYcG0yeG1jQ0lTNmNBemwwVDJGNUE4N0ZON0kKUEJOeXVrZDA3NEVCK1pCZEdncWE1aGNONTFwVWxJTml6cGV3RHhUS04wQXVLa2tYcCtlL0s4L2dRUit5QVpCYzRtdlFoRQpIQUt1aUc3emc4WEk3QS9iTDdRZXFhL2xPMkt4WFFCWFl6RC9LdFhpYzhORk4vSCt5NGl2eE41SHlvUDdGNHJ3bVZnK1E4CmpIK0YyVVVDNUxuNnZIWmM5TVl3VDVROHdlclVpK0ZTY01Td0dmQUFBQUF3RUFBUUFBQVFCampIODgxT1dxcVlWY25LMzIKbFV5Vkc1aklQK3paL3AzM3hiazZaZy9hZTkzZGhWeUt4QWxsT2UvYUhhVlpPTXBWbzNlZ1pzLzg4ZUlwZWZNalBQRjFPTgpLSlhRRmVDV1Ayd0wvNTlnOEloL2JrNlJLSXhvMHQ1UjJraXl6RTdZaVZwM3U5NnJMQjhiRkw1d2IrYkRHNlczaWZKWjVxClpWVllhMEI3UjNqcTV2eE9wK1VMQVRsT1cvT2s4Ynlla1NWWWtFZzRCS1hKUkVDYldCbEhCSjZvYjFiV1dNSHdUdVIyL2kKK1lZSW1zMVdvUmlxQytuVG9zdEhDUkV1b1FTSzUvMFdWT2pabitZVmUzV0g0UG1oNGU5ajF6N3hoTFNNVUpMZzFwZU1rMgowOXc3M1NMMitRK0lWenNMUGNTYTlSeWNwY3FPdUhJRUxjbE5JOWtNY1J2aEFBQUFnQytxb252WFdoVi8wWm9LRGc1NUdCClU4bWxjcDFudkFiWE9SeXExYzZVenBzYW54QVpyMHRFbHdPejR4bU15cnhtc1lpWFlock1xMUZ4R2RIQ3VFTTBaVW9QVnYKaVROTHJCQ0xNeE9POWJtKzNLT09QMGluR3MvV3d6Znp6VElPUnFaOElHM1hNbzAzNkNsWXJNQ1JUUUM1aVAyNjRpL3p2agpjaGQrWTdSVUJsQUFBQWdRRDhaM2swN0tlNVdyWW5aZ25YbWtsYy9FdHQrbFdZSm9EdVhjZnFreGo5blRkSGFWUHF2djlzCjdsWHRpd05mOWNlcHNVKzEzVkcyZllnQlBiSWcvcElVMGJwQ3FqK3F2U1hoc3BHVUltbkVvbENabFpINUVrL0wwZGhud3gKWU9MemZwUzJiOWZaWWhUdzZBcGtId0hBT24wcGxYenY1T1RxU1RtYlZIOE4vZ09RQUFBSUVBK25BbUxmdW9yVXJoWTc2WgoxdTdDTGpRSEczckdLMTJMR21EaTJpaFJiT0lRRU1xK3Nkc1Zzb2RFanJaWldXelJ6MkRSRVlQUTVGQ3h4T010bDI5Y0NtCkNjRVplQ1UzMlJHVENUaTgrbjR6bkdrdEJqQy9CMklvR0s0UVl6OWJjZWpPUFp6VWtRMkFRQkR6QnV4SVNoYlViZzRSeXQKaXdXeGFtbVB1NXFyd0pjQUFBQU5ibUZqYjNNdGFuZDBMV3RsZVFFQ0F3UUZCZz09Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
      - NACOS_AUTH_CACHE_ENABLE=true
      # Prometheus metrics 配置
      - NACOS_PROMETHEUS_METRICS_ENABLED=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - nacos-data:/home/nacos
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_HEAP_OPTS=-Xms512m -Xmx512m
    volumes:
      - kafka-data:/bitnami/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/9092' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yml" ]
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    command: [ "-config.file=/etc/promtail/config.yml" ]
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - promtail-positions:/positions
      - ./promtail-sd:/sd:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - app-logs:/app-logs:ro  # 添加应用日志目录挂载
    depends_on:
      - loki

  # Promtail 配置同步服务（从 Nacos 同步采集规则）
  promtail-config-sync:
    image: curlimages/curl:8.5.0
    container_name: promtail-config-sync
    command: [ "/bin/sh", "/scripts/sync-promtail-config.sh" ]
    volumes:
      - ./scripts/sync-promtail-config.sh:/scripts/sync-promtail-config.sh:ro
      - ./promtail-sd:/sd
    environment:
      - NACOS_HOST=nacos:8848
      - NACOS_DATA_ID=promtail-selectors
      - NACOS_GROUP=DEFAULT_GROUP
      - NACOS_NAMESPACE=public
    depends_on:
      - nacos
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_METRICS_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    ports:
      - "3000:3000"
    depends_on:
      - loki

  # Kafka metrics exporter (no SSL; best-practice for single-node initial monitoring)
  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.7.0
    container_name: kafka-exporter
    command: [ "--kafka.server=kafka:9092" ]
    ports:
      - "9308:9308"
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - loki
      - promtail
      - grafana
      - kafka-exporter

volumes:
  nacos-data:
  kafka-data:
  loki-data:
  grafana-data:
  promtail-positions:
  prom-data:
  app-logs:  # 统一的应用服务日志卷


